import { TemplateConfig } from '@/types';

export const templateConfigs: Record<string, TemplateConfig> = {
  ebook: {
    id: 'ebook',
    name: 'E-Book',
    description: 'Write comprehensive books with chapters and structure',
    icon: '📚',
    color: 'amber',
    bgGradient: 'from-amber-50 to-orange-50',
    sidebarTools: [
      { id: 'introduction', label: 'Introduction', icon: '✍️', action: 'add_introduction' },
      { id: 'chapters', label: 'Chapters', icon: '📖', action: 'manage_chapters' },
      { id: 'summary', label: 'Summary', icon: '📝', action: 'generate_summary' },
      { id: 'characters', label: 'Characters', icon: '👥', action: 'manage_characters' },
      { id: 'plot', label: 'Plot Builder', icon: '🎭', action: 'build_plot' },
      { id: 'research', label: 'Research Add-On', icon: '🔍', action: 'add_research' },
    ],
    aiSuggestions: [
      'Structure check',
      'Character consistency',
      'Pacing analysis',
      'Chapter summaries',
    ],
  },
  blog: {
    id: 'blog',
    name: 'Blog Post',
    description: 'SEO-optimized blog content with metadata',
    icon: '✨',
    color: 'blue',
    bgGradient: 'from-blue-50 to-cyan-50',
    sidebarTools: [
      { id: 'seo', label: 'SEO Tools', icon: '🎯', action: 'optimize_seo' },
      { id: 'faq', label: 'FAQ Generator', icon: '❓', action: 'generate_faq' },
      { id: 'headlines', label: 'Headline Variations', icon: '💡', action: 'generate_headlines' },
      { id: 'metadata', label: 'Meta Description', icon: '📊', action: 'generate_metadata' },
      { id: 'keywords', label: 'Keyword Research', icon: '🔑', action: 'research_keywords' },
      { id: 'outline', label: 'Content Outline', icon: '📋', action: 'create_outline' },
    ],
    aiSuggestions: [
      'SEO score',
      'Readability check',
      'Keyword density',
      'Meta suggestions',
    ],
  },
  social: {
    id: 'social',
    name: 'Social Media',
    description: 'Engaging social content with hooks and captions',
    icon: '🚀',
    color: 'purple',
    bgGradient: 'from-purple-50 to-pink-50',
    sidebarTools: [
      { id: 'hooks', label: 'Attention Hooks', icon: '🎣', action: 'generate_hooks' },
      { id: 'captions', label: 'A/B Captions', icon: '📱', action: 'generate_captions' },
      { id: 'trending', label: 'Trending Style', icon: '🔥', action: 'apply_trending' },
      { id: 'punchlines', label: 'Short Punchlines', icon: '💥', action: 'generate_punchlines' },
      { id: 'hashtags', label: 'Hashtag Generator', icon: '#️⃣', action: 'generate_hashtags' },
      { id: 'emojis', label: 'Emoji Enhancer', icon: '😊', action: 'add_emojis' },
    ],
    aiSuggestions: [
      'Engagement score',
      'Viral potential',
      'Platform optimization',
      'Best posting time',
    ],
  },
  poetry: {
    id: 'poetry',
    name: 'Poetry',
    description: 'Creative poetry with rhythm and metaphor tools',
    icon: '🌙',
    color: 'rose',
    bgGradient: 'from-rose-50 to-pink-50',
    sidebarTools: [
      { id: 'rhythm', label: 'Rhythm Check', icon: '🎵', action: 'check_rhythm' },
      { id: 'rhyme', label: 'Rhyme Finder', icon: '🎼', action: 'find_rhymes' },
      { id: 'metaphor', label: 'Metaphor Generator', icon: '🌟', action: 'generate_metaphors' },
      { id: 'imagery', label: 'Imagery Enhancer', icon: '🎨', action: 'enhance_imagery' },
      { id: 'style', label: 'Poetic Styles', icon: '📜', action: 'apply_style' },
    ],
    aiSuggestions: [
      'Meter analysis',
      'Emotional depth',
      'Imagery strength',
      'Stylistic consistency',
    ],
  },
  screenplay: {
    id: 'screenplay',
    name: 'Screenplay',
    description: 'Formatted screenplays with dialogue and scene structure',
    icon: '🎬',
    color: 'green',
    bgGradient: 'from-green-50 to-emerald-50',
    sidebarTools: [
      { id: 'scene', label: 'Scene Builder', icon: '🎞️', action: 'build_scene' },
      { id: 'dialogue', label: 'Dialogue Polish', icon: '💬', action: 'polish_dialogue' },
      { id: 'format', label: 'Format Check', icon: '📄', action: 'check_format' },
      { id: 'character_arc', label: 'Character Arcs', icon: '🎭', action: 'develop_arcs' },
      { id: 'beats', label: 'Story Beats', icon: '⚡', action: 'structure_beats' },
    ],
    aiSuggestions: [
      'Format compliance',
      'Dialogue naturalness',
      'Pacing analysis',
      'Character voice consistency',
    ],
  },
  research: {
    id: 'research',
    name: 'Research Paper',
    description: 'Academic writing with citations and methodology',
    icon: '🔬',
    color: 'slate',
    bgGradient: 'from-slate-50 to-gray-50',
    sidebarTools: [
      { id: 'citations', label: 'Citation Manager', icon: '📚', action: 'manage_citations' },
      { id: 'methodology', label: 'Methodology', icon: '🧪', action: 'structure_methodology' },
      { id: 'abstract', label: 'Abstract Generator', icon: '📋', action: 'generate_abstract' },
      { id: 'references', label: 'References', icon: '🔗', action: 'manage_references' },
      { id: 'data', label: 'Data Analysis', icon: '📊', action: 'analyze_data' },
    ],
    aiSuggestions: [
      'Citation accuracy',
      'Academic tone',
      'Logical flow',
      'Methodology clarity',
    ],
  },
  newsletter: {
    id: 'newsletter',
    name: 'Newsletter',
    description: 'Engaging newsletters with sections and CTAs',
    icon: '📧',
    color: 'indigo',
    bgGradient: 'from-indigo-50 to-blue-50',
    sidebarTools: [
      { id: 'subject', label: 'Subject Lines', icon: '💌', action: 'generate_subjects' },
      { id: 'cta', label: 'CTA Generator', icon: '🎯', action: 'generate_cta' },
      { id: 'sections', label: 'Section Builder', icon: '📑', action: 'build_sections' },
      { id: 'personalization', label: 'Personalization', icon: '👤', action: 'personalize' },
      { id: 'preview', label: 'Preview Text', icon: '👁️', action: 'generate_preview' },
    ],
    aiSuggestions: [
      'Open rate prediction',
      'Click-through optimization',
      'Engagement score',
      'Best send time',
    ],
  },
};
